/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedFerramentasRouteImport } from './routes/_authenticated/ferramentas'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedTarefasRouteRouteImport } from './routes/_authenticated/tarefas/route'
import { Route as AuthenticatedTarefasIndexRouteImport } from './routes/_authenticated/tarefas/index'
import { Route as AuthenticatedTarefasCalendarioRouteImport } from './routes/_authenticated/tarefas/calendario'
import { Route as AuthenticatedTarefasCronogramaRouteImport } from './routes/_authenticated/tarefas/cronograma'
import { Route as AuthenticatedTarefasListaRouteImport } from './routes/_authenticated/tarefas/lista'
import { Route as AuthenticatedTarefasProjetosRouteImport } from './routes/_authenticated/tarefas/projetos'
import { Route as AuthenticatedTarefasQuadroRouteImport } from './routes/_authenticated/tarefas/quadro'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFerramentasRoute =
  AuthenticatedFerramentasRouteImport.update({
    id: '/ferramentas',
    path: '/ferramentas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTarefasRouteRoute =
  AuthenticatedTarefasRouteRouteImport.update({
    id: '/tarefas',
    path: '/tarefas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTarefasIndexRoute =
  AuthenticatedTarefasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTarefasRouteRoute,
  } as any)
const AuthenticatedTarefasCalendarioRoute =
  AuthenticatedTarefasCalendarioRouteImport.update({
    id: '/calendario',
    path: '/calendario',
    getParentRoute: () => AuthenticatedTarefasRouteRoute,
  } as any)
const AuthenticatedTarefasCronogramaRoute =
  AuthenticatedTarefasCronogramaRouteImport.update({
    id: '/cronograma',
    path: '/cronograma',
    getParentRoute: () => AuthenticatedTarefasRouteRoute,
  } as any)
const AuthenticatedTarefasListaRoute =
  AuthenticatedTarefasListaRouteImport.update({
    id: '/lista',
    path: '/lista',
    getParentRoute: () => AuthenticatedTarefasRouteRoute,
  } as any)
const AuthenticatedTarefasProjetosRoute =
  AuthenticatedTarefasProjetosRouteImport.update({
    id: '/projetos',
    path: '/projetos',
    getParentRoute: () => AuthenticatedTarefasRouteRoute,
  } as any)
const AuthenticatedTarefasQuadroRoute =
  AuthenticatedTarefasQuadroRouteImport.update({
    id: '/quadro',
    path: '/quadro',
    getParentRoute: () => AuthenticatedTarefasRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/tarefas': typeof AuthenticatedTarefasRouteRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/ferramentas': typeof AuthenticatedFerramentasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/tarefas/calendario': typeof AuthenticatedTarefasCalendarioRoute
  '/tarefas/cronograma': typeof AuthenticatedTarefasCronogramaRoute
  '/tarefas/lista': typeof AuthenticatedTarefasListaRoute
  '/tarefas/projetos': typeof AuthenticatedTarefasProjetosRoute
  '/tarefas/quadro': typeof AuthenticatedTarefasQuadroRoute
  '/tarefas/': typeof AuthenticatedTarefasIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/ferramentas': typeof AuthenticatedFerramentasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/': typeof AuthenticatedIndexRoute
  '/tarefas/calendario': typeof AuthenticatedTarefasCalendarioRoute
  '/tarefas/cronograma': typeof AuthenticatedTarefasCronogramaRoute
  '/tarefas/lista': typeof AuthenticatedTarefasListaRoute
  '/tarefas/projetos': typeof AuthenticatedTarefasProjetosRoute
  '/tarefas/quadro': typeof AuthenticatedTarefasQuadroRoute
  '/tarefas': typeof AuthenticatedTarefasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ferramentas': typeof AuthenticatedFerramentasRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/tarefas/calendario': typeof AuthenticatedTarefasCalendarioRoute
  '/_authenticated/tarefas/cronograma': typeof AuthenticatedTarefasCronogramaRoute
  '/_authenticated/tarefas/lista': typeof AuthenticatedTarefasListaRoute
  '/_authenticated/tarefas/projetos': typeof AuthenticatedTarefasProjetosRoute
  '/_authenticated/tarefas/quadro': typeof AuthenticatedTarefasQuadroRoute
  '/_authenticated/tarefas/': typeof AuthenticatedTarefasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/tarefas'
    | '/admin'
    | '/ferramentas'
    | '/perfil'
    | '/tarefas/calendario'
    | '/tarefas/cronograma'
    | '/tarefas/lista'
    | '/tarefas/projetos'
    | '/tarefas/quadro'
    | '/tarefas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin'
    | '/ferramentas'
    | '/perfil'
    | '/'
    | '/tarefas/calendario'
    | '/tarefas/cronograma'
    | '/tarefas/lista'
    | '/tarefas/projetos'
    | '/tarefas/quadro'
    | '/tarefas'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/tarefas'
    | '/_authenticated/admin'
    | '/_authenticated/ferramentas'
    | '/_authenticated/perfil'
    | '/_authenticated/'
    | '/_authenticated/tarefas/calendario'
    | '/_authenticated/tarefas/cronograma'
    | '/_authenticated/tarefas/lista'
    | '/_authenticated/tarefas/projetos'
    | '/_authenticated/tarefas/quadro'
    | '/_authenticated/tarefas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ferramentas': {
      id: '/_authenticated/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof AuthenticatedFerramentasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas/': {
      id: '/_authenticated/tarefas/'
      path: '/'
      fullPath: '/tarefas/'
      preLoaderRoute: typeof AuthenticatedTarefasIndexRouteImport
      parentRoute: typeof AuthenticatedTarefasRouteRoute
    }
    '/_authenticated/tarefas/calendario': {
      id: '/_authenticated/tarefas/calendario'
      path: '/calendario'
      fullPath: '/tarefas/calendario'
      preLoaderRoute: typeof AuthenticatedTarefasCalendarioRouteImport
      parentRoute: typeof AuthenticatedTarefasRouteRoute
    }
    '/_authenticated/tarefas/cronograma': {
      id: '/_authenticated/tarefas/cronograma'
      path: '/cronograma'
      fullPath: '/tarefas/cronograma'
      preLoaderRoute: typeof AuthenticatedTarefasCronogramaRouteImport
      parentRoute: typeof AuthenticatedTarefasRouteRoute
    }
    '/_authenticated/tarefas/lista': {
      id: '/_authenticated/tarefas/lista'
      path: '/lista'
      fullPath: '/tarefas/lista'
      preLoaderRoute: typeof AuthenticatedTarefasListaRouteImport
      parentRoute: typeof AuthenticatedTarefasRouteRoute
    }
    '/_authenticated/tarefas/projetos': {
      id: '/_authenticated/tarefas/projetos'
      path: '/projetos'
      fullPath: '/tarefas/projetos'
      preLoaderRoute: typeof AuthenticatedTarefasProjetosRouteImport
      parentRoute: typeof AuthenticatedTarefasRouteRoute
    }
    '/_authenticated/tarefas/quadro': {
      id: '/_authenticated/tarefas/quadro'
      path: '/quadro'
      fullPath: '/tarefas/quadro'
      preLoaderRoute: typeof AuthenticatedTarefasQuadroRouteImport
      parentRoute: typeof AuthenticatedTarefasRouteRoute
    }
  }
}

interface AuthenticatedTarefasRouteRouteChildren {
  AuthenticatedTarefasCalendarioRoute: typeof AuthenticatedTarefasCalendarioRoute
  AuthenticatedTarefasCronogramaRoute: typeof AuthenticatedTarefasCronogramaRoute
  AuthenticatedTarefasListaRoute: typeof AuthenticatedTarefasListaRoute
  AuthenticatedTarefasProjetosRoute: typeof AuthenticatedTarefasProjetosRoute
  AuthenticatedTarefasQuadroRoute: typeof AuthenticatedTarefasQuadroRoute
  AuthenticatedTarefasIndexRoute: typeof AuthenticatedTarefasIndexRoute
}

const AuthenticatedTarefasRouteRouteChildren: AuthenticatedTarefasRouteRouteChildren =
  {
    AuthenticatedTarefasCalendarioRoute: AuthenticatedTarefasCalendarioRoute,
    AuthenticatedTarefasCronogramaRoute: AuthenticatedTarefasCronogramaRoute,
    AuthenticatedTarefasListaRoute: AuthenticatedTarefasListaRoute,
    AuthenticatedTarefasProjetosRoute: AuthenticatedTarefasProjetosRoute,
    AuthenticatedTarefasQuadroRoute: AuthenticatedTarefasQuadroRoute,
    AuthenticatedTarefasIndexRoute: AuthenticatedTarefasIndexRoute,
  }

const AuthenticatedTarefasRouteRouteWithChildren =
  AuthenticatedTarefasRouteRoute._addFileChildren(
    AuthenticatedTarefasRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedTarefasRouteRoute: typeof AuthenticatedTarefasRouteRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedFerramentasRoute: typeof AuthenticatedFerramentasRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedTarefasRouteRoute: AuthenticatedTarefasRouteRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedFerramentasRoute: AuthenticatedFerramentasRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
